# Generated by Django 5.1.7 on 2025-04-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclebag',
            name='weight',
        ),
        migrations.AddField(
            model_name='recyclebag',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
