# Generated by Django 5.1.7 on 2025-03-20 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recyclebag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanneditem',
            name='item_name',
        ),
        migrations.AddField(
            model_name='scanneditem',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanneditem',
            name='material_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('glass', 'Glass'), ('metal', 'Metal')], default='plastic', max_length=10),
        ),
        migrations.CreateModel(
            name='RecycledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('plastic', 'Plastic'), ('glass', 'Glass'), ('can', 'Can')], max_length=10)),
                ('weight', models.FloatField()),
                ('points', models.IntegerField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
