# Generated by Django 5.1.7 on 2025-03-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_scanneditem_item_name_scanneditem_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycleditem',
            name='weight',
        ),
        migrations.AddField(
            model_name='recycleditem',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
