# Generated by Django 5.1.7 on 2025-03-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_recycleditem_count_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclebag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recyclebag',
            name='name',
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('can', 'Can'), ('glass', 'Glass')], default='plastic', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='RecycledItem',
        ),
    ]
