# Generated by Django 5.2 on 2025-04-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_recycleitem_material_remove_scanneditem_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
            ],
        ),
    ]
