# Generated by Django 5.2 on 2025-04-14 02:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_recycleditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycleditem',
            name='date_recycled',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
