# Generated by Django 5.2 on 2025-04-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_recycleditem_date_recycled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycleditem',
            name='weight',
        ),
        migrations.AddField(
            model_name='recycleditem',
            name='count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recycleditem',
            name='date_recycled',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
